---
# tasks file for minecraft
- name: Download minecraft
  ansible.builtin.get_url:
    url: https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar
    dest: /tmp/server.jar
    mode: '0440'
