---
- name: Apply roles
  hosts: all
  remote_user: ansible
  become: true

  vars:
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=accept-new"

  roles:
    - set_timezone
    - install_apps
    - manage_ansible_user
