---
- name: Update servers
  hosts: all
  remote_user: root

  tasks:
  - name: Update Cache
    ansible.builtin.apt:
      name: "*"
      update_cache: yes

  - name: Update servers
    ansible.builtin.package:
      name: "*"
      state: latest

  - name: Check if a reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: no
    register: reboot_required_file 

  - name: Reboot the server (If Required)
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  - name : Remove dependencies that are no longer reboot_required.
    ansible.builtin.apt:
      autoremove: yes
